"""empty message

Revision ID: 9603cc1f520d
Revises: f7a9980d6500
Create Date: 2025-02-02 15:55:54.366929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9603cc1f520d'
down_revision = 'f7a9980d6500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['film_id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['people_id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['planet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
